### ISSUE TITLE
slide 2-44: squares() is not called

### ISSUE THREAD

**Issue by arturtamborski** [dabeaz-course/python-mastery#19]
Thank you very very much for this material. It's amazing! I'm super grateful for it.

I think I spotted a small error in the code on slide 2-44:
```diff
-for n in squares:
+for n in squares([1, 2, 3, 4, 5]):
```

I think the squares should be called to be effective.

Thank you again for sharing your knowledge.

**Comment by dabeaz** [comment]
Good catch!   I've corrected the source material.  Will appear in the PDF the next time I update it.

**Comment by dabeaz** [comment]
Fixed.
