### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by mohasha92** [dabeaz-course/python-mastery#22]
WHERE CAN I GET JAVASCRIPT LIKE THIS PLEASE?

**Comment by Patish11** [comment]
> WHERE CAN I GET JAVASCRIPT LIKE THIS PLEASE?

**Comment by dabeaz** [comment]
Don't know, but it won't be by me!

**Comment by Patish11** [comment]
> WHERE CAN I GET JAVASCRIPT LIKE THIS PLEASE?

**Comment by DavidPesticcio** [comment]
> WHERE CAN I GET JAVASCRIPT LIKE THIS PLEASE?

FYI @mohasha92 / @Patish11 - You could try the link below...

[Software Design by Example: a tool-based introduction with JavaScript.](https://third-bit.com/sdxjs/)
