### ISSUE TITLE
Exercise 2.6c asks to compare memory use with unknown other state

### ISSUE THREAD

**Issue by l0b0** [dabeaz-course/python-mastery#30]
> The memory should drop quite a bit.

in `Exercises/ex2_6.md` seems like a non sequitur, because there was no previous `tracemalloc.get_traced_memory()` call in the same exercise.

**Comment by dabeaz** [comment]
Exercise 2.1 has measurements of memory use.   Perhaps a link should be added.

**Comment by dabeaz** [comment]
Added a few links to earlier exercises.
