### ISSUE TITLE
Missing recommendation in Exercise 7.2

### ISSUE THREAD

**Issue by jy-gh** [dabeaz-course/python-mastery#50]
The **Discussion** at the end of Exercise 7.2 says the following:

> Writing robust decorators is often a lot harder than it looks. Recommended reading:

However, there's no recommendation. Perhaps it was omitted accidentally?

**Comment by dabeaz** [comment]
Oh yeah.  Probably an error in format conversion.  Let me see if I can dig that up.  It's meant to be a reference to well-known blog post about "How you're writing your decorator is wrong."

**Comment by dabeaz** [comment]
Added reading reference.
