### ISSUE TITLE
Missing information in exercise 2.5 (e) Challenge

### ISSUE THREAD

**Issue by jarlethorsen** [dabeaz-course/python-mastery#56]
Your challenge is to modify the **RideData** class, however to show the expected result you use **readrides.read_rides_as_columns()** as an example and this method does not currently return a RideData object...

Should this method also be modified to return a RideData object? Otherwise modifying RideData will have no affect on the output of **readrides.read_rides_as_columns()** ?

https://github.com/dabeaz-course/python-mastery/blob/afec76dd943b292492b4c6badd500d3fb947812f/Exercises/ex2_5.md?plain=1#L295-L302

**Comment by Curiosit** [comment]
I believe there is an error here and it should be about the `read_rides_as_dicts` function?
Also - there is no solution in this excercise...

**Comment by dabeaz** [comment]
Changed to use `read_rides_as_dicts`.
