### ISSUE TITLE
Add answers to ex2_2

### ISSUE THREAD

**Issue by jordanspangenberg** [dabeaz-course/python-mastery#57]
Even if you don't include an implementation, you should include the correct results for the exercise prompt.

How many bus routes exist in Chicago?

'Number of unique routes:'
181

How many people rode the number 22 bus on February 2, 2011? What about any route on any date of your choosing?

'Number of route 22 riders on 02/02/2011:'
[Row(route='22', date='02/02/2011', daytype='W', rides=5055)]

What is the total number of rides taken on each bus route?

'Most popular routes:'
[('79', 133796763), ('9', 117923787), ('49', 95915008)]

What five bus routes had the greatest ten-year increase in ridership from 2001 to 2011?

'Route with most increase in passengers between 2001 and 2011:'
[('15', 2732209),
 ('147', 2107910),
 ('66', 1612958),
 ('12', 1612067),
 ('14', 1351308)]

**Comment by dabeaz** [comment]
Good idea. Added to the solution page.
