### ISSUE TITLE
typo 'allrices' in PythonMastery.pdf

### ISSUE THREAD

**Issue by cdump** [dabeaz-course/python-mastery#6]
On page 98 (2-27):
```
>>> allrices['HPE']
34.23
>>> allprices['F']
51.1
>>>
```

Should be `>>> allprices['HPE']`

**Comment by dabeaz** [comment]
Thanks for the catch.   Regenerating the PDF is somewhat involved, but this will be fixed the next time I post an update (I may wait a little while to see if other typos are spotted first).

**Comment by ldo** [comment]
You should add a script to build the PDF file. Then you can delete the PDF file itself from the source tree, since it is difficult to manage under version control anyway.

**Comment by dabeaz** [comment]
There are a lot of things I could do.  This is not one of them.  Sorry.

**Comment by dabeaz** [comment]
Fixed.
