### ISSUE TITLE
Slide 3-75 in pdf: Wording of handler usage

### ISSUE THREAD

**Issue by rmarvie** [dabeaz-course/python-mastery#9]
The handler is the same object isn't it?

Should the sentence:

> Notice how various steps of the algorithm are deferred to a separate handler object

Be phrased:

Notice how various steps of the algorithm are deferred to a separate *(method|function) of the* handler object

**Comment by dabeaz** [comment]
Going to leave as is for brevity.   The key idea is that a separate object is involved.

**Comment by rmarvie** [comment]
definitely make sense.
